 .gitignore                                                                      |   0
 accounts/__init__.py                                                            |   0
 accounts/admin.py                                                               |   0
 accounts/apps.py                                                                |   0
 accounts/email_templates/reset_password.txt                                     |   0
 accounts/email_templates/verify_email.txt                                       |   0
 accounts/migrations/0001_initial.py                                             |   0
 accounts/migrations/0002_user_phone_number_user_updated_at.py                   |   0
 accounts/migrations/0003_user_manager.py                                        |   0
 .../0004_remove_user_manager_user_address_user_description_and_more.py          |   0
 accounts/migrations/0005_manageruserassociation.py                              |   0
 accounts/migrations/0006_manageruserassociation_uniq_manager_user_pair.py       |   0
 accounts/migrations/0007_alter_user_role.py                                     |   0
 accounts/migrations/0008_alter_user_username.py                                 |   0
 accounts/migrations/0009_alter_user_username.py                                 |   0
 accounts/migrations/__init__.py                                                 |   0
 accounts/models.py                                                              |   0
 accounts/permissions.py                                                         |   0
 accounts/serializers.py                                                         |   0
 accounts/signals.py                                                             |   0
 accounts/tests.py                                                               |   0
 accounts/tokens.py                                                              |   0
 accounts/urls.py                                                                |   0
 accounts/validators.py                                                          |   0
 accounts/views.py                                                               |   0
 afdd/__init__.py                                                                |   0
 afdd/asgi.py                                                                    |   0
 afdd/settings.py                                                                |   2 [32m+[m[31m-[m
 afdd/urls.py                                                                    |   0
 afdd/wsgi.py                                                                    |   0
 devices/__init__.py                                                             |   0
 devices/admin.py                                                                |   0
 devices/apps.py                                                                 |   0
 devices/auto-annotation-461106-c1934e2fdd95.json                                |   0
 devices/migrations/0001_initial.py                                              |   0
 devices/migrations/0002_event.py                                                |   0
 devices/migrations/0003_heartbeat.py                                            |   0
 devices/migrations/0004_violation.py                                            |   0
 devices/migrations/0005_vehicle.py                                              |   0
 devices/migrations/0006_driver.py                                               |   0
 devices/migrations/0007_remove_driver_vehicle.py                                |   0
 devices/migrations/0008_driverassignment.py                                     |   0
 devices/migrations/0009_driverassignment_created_at_and_more.py                 |   0
 devices/migrations/0010_driver_rfid_tag_driverassignment_latitude_and_more.py   |   0
 devices/migrations/0011_driverassignment_device.py                              |   0
 devices/migrations/0012_alter_driverassignment_vehicle.py                       |   0
 devices/migrations/0013_alter_driverassignment_assigned_at.py                   |   0
 devices/migrations/0014_remove_driverassignment_vehicle.py                      |   0
 devices/migrations/0015_violation_user_violation_vehicle.py                     |   0
 devices/migrations/0016_alter_violation_user_alter_violation_vehicle.py         |   0
 devices/migrations/0017_violation_device_viol_logged__4123bc_idx_and_more.py    |   0
 devices/migrations/0018_alter_vehicle_device.py                                 |   0
 devices/migrations/0019_violationannotation.py                                  |   0
 devices/migrations/0020_alter_violation_status.py                               |   0
 devices/migrations/__init__.py                                                  |   0
 devices/models.py                                                               |   0
 devices/serializers.py                                                          |   0
 devices/tests.py                                                                |   0
 devices/urls.py                                                                 |   0
 devices/views.py                                                                |   0
 geofences.dump                                                                  | Bin [31m4443427[m -> [32m4443427[m bytes
 globals.sql                                                                     |   0
 globals.sqlpg_dumpall                                                           |   0
 manage.py                                                                       |   0
 requirements.txt                                                                | Bin [31m1628[m -> [32m1628[m bytes
 temp_tail.txt                                                                   |   0
 temp_tail_head.txt                                                              |   0
 violations/__init__.py                                                          |   0
 violations/admin.py                                                             |   0
 violations/apps.py                                                              |   0
 violations/management/__init__.py                                               |   0
 violations/management/commands/__init__.py                                      |   0
 violations/management/commands/seed_violations.py                               |   0
 violations/migrations/0001_initial.py                                           |   0
 violations/migrations/__init__.py                                               |   0
 violations/models.py                                                            |   0
 violations/serializers.py                                                       |   0
 violations/tests.py                                                             |   0
 violations/urls.py                                                              |   0
 violations/views.py                                                             |   6 [32m+++[m[31m---[m
 80 files changed, 4 insertions(+), 4 deletions(-)
