# Generated by Django 5.2.6 on 2025-10-02 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(help_text='Event time from device (original source)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device', to_field='uuid')),
            ],
            options={
                'db_table': 'device_events',
                'indexes': [models.Index(fields=['device', 'logged_at'], name='device_even_device__9ceb15_idx'), models.Index(fields=['type'], name='device_even_type_de9e47_idx')],
            },
        ),
    ]
