# Generated by Django 5.2.6 on 2025-10-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_heartbeat'),
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(help_text='Event time from device (original source)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('front_camera_video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rear_camera_video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('left_camera_video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('right_camera_video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cabin_camera_video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meta', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='devices.device', to_field='uuid')),
                ('violation_type_id', models.ForeignKey(db_column='violation_id', on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='violations.violationtype')),
            ],
            options={
                'db_table': 'device_violations',
                'indexes': [models.Index(fields=['device', 'logged_at', 'violation_type_id'], name='device_viol_device__e911b2_idx')],
            },
        ),
    ]
