# Generated by Django 5.2.6 on 2025-10-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
    ]
