# Generated by Django 5.2.6 on 2025-10-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_driver_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='devices.driver')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='devices.vehicle')),
            ],
        ),
    ]
