# Generated by Django 5.2.6 on 2025-10-24 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_driverassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
