# Generated by Django 5.2.6 on 2025-10-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_driverassignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rfid_tag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverassignment',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
