# Generated by Django 5.2.6 on 2025-10-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_driver_rfid_tag_driverassignment_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverassignment',
            name='device',
            field=models.ForeignKey(db_column='device_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='devices.device', to_field='uuid'),
            preserve_default=False,
        ),
    ]
