# Generated by Django 5.2.6 on 2025-10-27 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_driverassignment_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverassignment',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_column='vehicle_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='devices.vehicle'),
        ),
    ]
