# Generated by Django 5.2.6 on 2025-10-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_driverassignment_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverassignment',
            name='assigned_at',
            field=models.DateTimeField(help_text='Driver Assign time from device (original source)'),
        ),
    ]
