# Generated by Django 5.2.6 on 2025-10-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_alter_driverassignment_assigned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverassignment',
            name='vehicle',
        ),
    ]
