# Generated by Django 5.2.6 on 2025-11-03 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_remove_driverassignment_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violation',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='devices.vehicle'),
            preserve_default=False,
        ),
    ]
