# Generated by Django 5.2.6 on 2025-11-03 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_alter_violation_user_alter_violation_vehicle'),
        ('violations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['logged_at'], name='device_viol_logged__4123bc_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['status'], name='device_viol_status_69ce1b_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['user'], name='device_viol_user_id_2e9d63_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['vehicle'], name='device_viol_vehicle_b28c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['violation_type_id'], name='device_viol_violati_217b18_idx'),
        ),
    ]
