# Generated by Django 5.2.6 on 2025-11-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_violation_device_viol_logged__4123bc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='device',
            field=models.OneToOneField(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='devices.device', to_field='uuid'),
        ),
    ]
