# Generated by Django 5.2.6 on 2025-11-12 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_vehicle_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotated_by', models.ForeignKey(db_column='annotated_by', on_delete=django.db.models.deletion.CASCADE, related_name='violation_annotations', to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(db_column='violation_id', on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='devices.violation')),
            ],
            options={
                'db_table': 'violation_annotations',
                'indexes': [models.Index(fields=['violation', 'annotated_by', 'status', 'created_at'], name='violation_a_violati_5716d0_idx')],
            },
        ),
    ]
