# Generated by Django 5.2.6 on 2025-12-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_violationannotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(default='unevaluated', max_length=100),
        ),
    ]
