# Generated by Django 5.2.6 on 2026-03-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_violation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
