# Generated by Django 5.2.6 on 2026-05-14 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverassignment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Assigned Driver'), (-1, 'Driver Not Detected'), (0, 'Empty Seat')], default=1),
        ),
        migrations.AlterField(
            model_name='driverassignment',
            name='driver',
            field=models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='devices.driver'),
        ),
    ]
