# Generated by Django 5.2.6 on 2025-11-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_manageruserassociation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manageruserassociation',
            constraint=models.UniqueConstraint(fields=('manager', 'user'), name='uniq_manager_user_pair'),
        ),
    ]
