# Generated by Django 5.2.6 on 2025-11-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_manageruserassociation_uniq_manager_user_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User'), ('annotator', 'Annotator')], default='user', max_length=20),
        ),
    ]
