# Generated by Django 5.2.6 on 2025-12-10 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Enter a valid username. Spaces are allowed inside, but not at the beginning or end.', regex='^(?!\\s)[\\w.@+\\-\\s]+(?<!\\s)$')], verbose_name='username'),
        ),
    ]
