"""
Django settings for afdd project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in your environment. The insecure default is only for local dev.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-n_p(96h2ox&s&fy2yxnsije54=f%xs!f6k_k@)@8s-9q2sm9#s'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DJANGO_DEBUG=False in your environment for production.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['192.168.100.10','192.168.100.19','127.0.0.1','localhost','182.180.188.205',"backend.monit.pk","192.168.100.200","backend.monit.tech","afdd.monit.tech","engro-production.vercel.app","34.18.103.11","afdd-production-git-development-askari7s-projects.vercel.app","afdd-portal.vercel.app",".vercel.app"]


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
   "accounts.apps.AccountsConfig",
    "devices.apps.DevicesConfig",
    "violations.apps.ViolationsConfig",
    "analytics.apps.AnalyticsConfig",
    "drf_spectacular",
    "drf_spectacular_sidecar",

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# Restrict CORS to known origins in production.
# Override by setting CORS_ALLOW_ALL_ORIGINS=True in the environment (local dev only).
if os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True':
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.environ.get(
            'CORS_ALLOWED_ORIGINS',
            'http://localhost:3000,http://localhost:5173,https://engro-production.vercel.app,https://secmc.monit.tech,https://afdd-portal.monit.tech,https://afdd-production.vercel.app,https://afdd-next.vercel.app,https://afdd-production-git-development-askari7s-projects.vercel.app'
        ).split(',')
        if o.strip()
    ]

ROOT_URLCONF = 'afdd.urls'
AUTH_USER_MODEL = "accounts.User"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"  # configure creds
DEFAULT_FROM_EMAIL = "no-reply@example.com"  # change

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_THROTTLE_RATES": {"anon": "20/min", "user": "60/min"},
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
WSGI_APPLICATION = 'afdd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_DATABASE_URL = os.environ.get("DATABASE_URL")
DATABASES = {
    "default": dj_database_url.parse(_DATABASE_URL, conn_max_age=600, ssl_require=True)
    if _DATABASE_URL
    else {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "devices": {"handlers": ["console"], "level": "WARNING", "propagate": False},
    },
}





REST_FRAMEWORK.update({
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
})

SPECTACULAR_SETTINGS = {
    "TITLE": "AFDD Project API",
    "DESCRIPTION": "API documentation for frontend integration.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # we’ll expose schema at a clean URL
    # JWT Security Scheme (SimpleJWT)
    "AUTHENTICATION_WHITELIST": [],  # leave blank
    "COMPONENT_SPLIT_REQUEST": True,
    "SECURITY": [{"BearerAuth": []}],
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    "CONTACT": {"name": "Team", "email": "dev@yourdomain.com"},
    "LICENSE": {"name": "Proprietary"},
    "SERVE_PERMISSIONS": [],  # keep public in dev; lock down in prod (see tips below)
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
}
# SPECTACULAR_SETTINGS["SERVE_PERMISSIONS"] = ["rest_framework.permissions.IsAdminUser"]
SPECTACULAR_SETTINGS["SCHEMA_PATH_PREFIX"] = r"/api"
SPECTACULAR_SETTINGS["CAMELIZE_NAMES"] = False
SPECTACULAR_SETTINGS["TAGS"] = [
    {"name": "Auth", "description": "Authentication & accounts"},
    {"name": "Vehicles", "description": "Vehicle CRUD"},
    # ...
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
]